### ISSUE TITLE
Scores for Tissue specific ChIP Seq data

### ISSUE THREAD

**Issue by OldManTae** [wassermanlab/MANTA2#1]
Hello,

MANTA2 seems like a very convenient tool! It performed very quickly for a quick test analysis that I ran!

I am interested in using MANTA2 for analyses that are mostly brain development related. While MANTA2 has been useful for a preliminary look how variants may affect any TFBS, I was wondering if it was possible to limit the search to brain related ChIP seq data.

I was considering recalculating the scores to do this (looking at jaspar2remap folder), but I had a couple of questions while doing so - 

1.  Why are the ENCODE and GEO datasets needed separately in different folders (is the ChIP peak file from remap not sufficient? Or was this due to an old formatting issue?)
2. Is there anything about the scripts/pipeline that prevents this from working on hg19?
3. Are there any concerns with taking a tissue specific subset to calculate scores?
4. Is it possible to recalculate scores with say ChIP-atlas peaks (or any other database?)
5. Is it possible to output the scores in more annotation pipeline friendly output? (eg compatible with vcfanno or annovar)

Thank you in advance for your time!

Best,

Tae

**Comment by oriolfornes** [comment]
Hi Tae,

Thank you for your positive feedback!

For **1**, note that the separation between ENCODE and GEO datasets is internal to ReMap. The following is an extract from the 2018 paper:

> The ReMap 2015 resource created a large catalog of regulatory regions by compiling the genomic localization of 132 different TRs across 83 different human cell lines and tissue types based on 395 non-ENCODE datasets selected from Gene Expression Omnibus (2) and ArrayExpress (3). This catalog was merged with the ENCODE multi-cell peaks (5), generating a global map of 13M regulatory elements for 237 TRs across multiple cell types. However, since the 2015 publication of ReMap, an even greater number of ChIP-seq assays has been submitted to genomic data repositories.

Generally speaking, ENCODE datasets are of higher quality than those from GEO.

For **2**, briefly the answer is no. In theory, it is possible to adapt MANTA2 to hg19 or mouse assemblies (provided that ChIP-seq peaks are intersected with transcription factor binding site predictions within the genomic context of these assemblies). However, we focused on hg38 because, at the time for publication, it was the only genome assembly available on ReMap. Note that **reprocessing ChIP-seq datasets is an extremely computationally expensive task**. To surpass such limitation, within the MANTA2 manuscript, we show that a simple [liftOver](https://genome.ucsc.edu/cgi-bin/hgLiftOver) can be used to adapt the tool to hg19:

> We downloaded ChIP-seq data for 35,703 TF-binding events at heterozygous sites in GM12878 and HeLa cells for 36 different TFs18. For each event, allelic imbalance was calculated as the number of ChIP-seq reads mapped on the alternate allele divided by the total number of reads mapped at that position (Fig. 2a). The coordinates from the original publication refer to the hg19 version of the human genome; we used the liftOver tool from the UCSC Genome Browser23 to convert them to the hg38 assembly (the conversion process failed for 12 coordinates).

For **3**, MANTA2 scores are the same regardless of tissue/sample. However, you might want to filter the results from MANTA2 a posteriori. For instance, imagine that MANTA2 predicts that binding sites for TFs 1, 2 and 3 are impacted, but from RNA-seq, you know that only TF 1 is relevant to your samples of interest.

For **4**, yes, it is possible. You simply need to intersect your ChIP-seq peaks with the [TFBS predictions](http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2018/hg38/tsv/). For your information, the next releases of JASPAR and ReMap are underway.

For **5**, I have never worked with these tools, but I assume it should not be extremely difficult.

**Comment by OldManTae** [comment]
Great, thank you for the prompt reply (and addressing my questions well)!
